services:
  jekyll:
    build: .
    user: "${UID:-1000}:${GID:-1000}"
    command: bundle exec jekyll serve --host 0.0.0.0 --force_polling
    ports:
      - "4000:4000"
    volumes:
      - .:/site
